# Stage 1: Build React App
FROM node:18-alpine as build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:1.21.6-alpine

# Copy built React app to Nginx public directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the Nginx template instead of the final config
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template

# Copy Runtime Environment Script
COPY env.sh /docker-entrypoint.d/env.sh
RUN chmod +x /docker-entrypoint.d/env.sh

# Expose port
EXPOSE 80

# Start Nginx
CMD ["/docker-entrypoint.d/env.sh"]
